global using System;
global using System.Collections.Generic;
global using System.Linq;
global using HarmonyLib;
global using JetBrains.Annotations;
global using JFUtils;
global using UnityEngine;
global using static JFUtils.ModBase;
global using static KilnReimagined.Plugin;
global using Debug = UnityEngine.Debug;
global using Object = UnityEngine.Object;